from grow.model.album.Fields import Fields as AlbumFields


class Fields:
    CREATED_ON = AlbumFields.CREATED_ON
    UPDATED_ON = AlbumFields.UPDATED_ON
    UUID = AlbumFields.UUID
    NAME_PUBLIC = AlbumFields.NAME_PUBLIC
    YEAR = AlbumFields.YEAR
    ALBUM_ARTISTS = AlbumFields.ALBUM_ARTISTS
    UPLOADED_TRACKS_NOT_ARCHIVED_SORTED_INTERNAL = AlbumFields.UPLOADED_TRACKS_NOT_ARCHIVED_SORTED_INTERNAL
    UPLOADED_TRACKS_NOT_ARCHIVED_SORTED_PUBLIC = AlbumFields.UPLOADED_TRACKS_NOT_ARCHIVED_SORTED_PUBLIC
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_INTERNAL = AlbumFields.UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_INTERNAL
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = AlbumFields.UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC
    UPLOADED_TRACKS_ARCHIVED_COUNT_INTERNAL = AlbumFields.UPLOADED_TRACKS_ARCHIVED_COUNT_INTERNAL
    UPLOADED_TRACKS_ARCHIVED_COUNT_PUBLIC = AlbumFields.UPLOADED_TRACKS_ARCHIVED_COUNT_PUBLIC
