# Generated by Django 5.2.8 on 2026-08-13 08:48

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.AppForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("the_music_tree_genre_kit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("play_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "db_table": "grow_playlist",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("_name", the_music_tree_api_kit.field.AppCharField(db_column="name", default=None, max_length=256)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "grow_artist",
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("_name", the_music_tree_api_kit.field.AppCharField(db_column="name", default=None, max_length=256)),
                ("year", the_music_tree_api_kit.field.AppCharField(default=None, max_length=4, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "album_artists",
                    the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(
                        related_name="albums", to="grow.artist"
                    ),
                ),
            ],
            options={
                "db_table": "grow_album",
            },
        ),
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("_name", the_music_tree_api_kit.field.AppCharField(db_column="name", max_length=256)),
                (
                    "parent",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="grow.criteria",
                    ),
                ),
                (
                    "root",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="descendants", to="grow.criteria"
                    ),
                ),
                (
                    "type",
                    the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="the_music_tree_genre_kit.criteriatype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Criteria",
                "verbose_name_plural": "Criterias",
                "db_table": "grow_criteria",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[],
            options={
                "db_table": "grow_genre",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("grow.criteria",),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[],
            options={
                "db_table": "grow_tag",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("grow.criteria",),
        ),
        migrations.CreateModel(
            name="CriteriaLineageRel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("degree", models.PositiveIntegerField()),
                (
                    "ascendant",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="descendants_rels", to="grow.criteria"
                    ),
                ),
                (
                    "descendant",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ascendants_rels", to="grow.criteria"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Criteria Lineage Relation",
                "verbose_name_plural": "Criteria Lineage Relations",
                "db_table": "grow_criteria_lineage_rel",
            },
        ),
        migrations.AddField(
            model_name="criteria",
            name="ascendants",
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(
                through="grow.CriteriaLineageRel", through_fields=("descendant", "ascendant"), to="grow.criteria"
            ),
        ),
        migrations.CreateModel(
            name="CriteriaPlaylist",
            fields=[
                (
                    "playlist",
                    the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="criteria_playlist",
                        serialize=False,
                        to="grow.playlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Criteria Playlist",
                "verbose_name_plural": "Criteria Playlists",
                "db_table": "grow_criteria_playlist",
            },
            bases=("grow.playlist",),
        ),
        migrations.CreateModel(
            name="ManualPlaylist",
            fields=[
                (
                    "playlist",
                    the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="manual_playlist",
                        serialize=False,
                        to="grow.playlist",
                    ),
                ),
                ("_name", the_music_tree_api_kit.field.AppCharField(db_column="name", max_length=256)),
            ],
            options={
                "verbose_name": "Manual Playlist",
                "verbose_name_plural": "Manual Playlists",
                "db_table": "grow_manual_playlist",
            },
            bases=("grow.playlist",),
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("content_uuid", models.UUIDField(db_column="object_pk")),
                (
                    "content_type",
                    the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Play",
                "verbose_name_plural": "Plays",
                "db_table": "grow_play",
            },
        ),
        migrations.CreateModel(
            name="UploadedTrack",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("title", the_music_tree_api_kit.field.AppCharField(max_length=256)),
                (
                    "track_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "language",
                    the_music_tree_api_kit.field.AppCharField(blank=True, default=None, max_length=3, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "album",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_tracks_of_album",
                        to="grow.album",
                    ),
                ),
                (
                    "artists",
                    the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(
                        blank=True, related_name="uploaded_tracks_of_artist", to="grow.artist"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded Track",
                "verbose_name_plural": "Uploaded Tracks",
                "db_table": "grow_uploaded_track",
            },
        ),
        migrations.CreateModel(
            name="UploadedTrackPlaylistRel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "playlist",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_track_playlist_rels",
                        to="grow.playlist",
                    ),
                ),
                (
                    "uploaded_track",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_track_playlist_rels",
                        to="grow.uploadedtrack",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded Track Playlist Relation",
                "verbose_name_plural": "Uploaded Track Playlist Relations",
                "db_table": "grow_uploaded_track_playlist_rel",
            },
        ),
        migrations.AddField(
            model_name="uploadedtrack",
            name="playlists",
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(
                related_name="uploaded_tracks_of_playlist", through="grow.UploadedTrackPlaylistRel", to="grow.playlist"
            ),
        ),
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.CheckConstraint(
                condition=models.Q(("_name", ""), _negated=True), name="artist_non_empty_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.CheckConstraint(
                condition=models.Q(("_name", ""), _negated=True), name="album_non_empty_name"
            ),
        ),
        migrations.AddField(
            model_name="uploadedtrack",
            name="genre",
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="uploaded_tracks_of_criteria",
                to="grow.genre",
            ),
        ),
        migrations.AddIndex(
            model_name="criterialineagerel",
            index=models.Index(fields=["user"], name="crit_lineage_rel_user_idx"),
        ),
        migrations.AddIndex(
            model_name="criteria",
            index=models.Index(fields=["user", "_name"], name="criteria_user_name_idx"),
        ),
        migrations.AddIndex(
            model_name="criteria",
            index=models.Index(fields=["user", "uuid"], name="criteria_user_uuid_idx"),
        ),
        migrations.AddConstraint(
            model_name="criteria",
            constraint=models.CheckConstraint(
                condition=models.Q(("_name", ""), _negated=True), name="criteria_non_empty_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="criteria",
            constraint=models.UniqueConstraint(fields=("user", "_name"), name="unique_name_per_user"),
        ),
        migrations.AddField(
            model_name="criteriaplaylist",
            name="criteria",
            field=the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria_playlist",
                to="grow.criteria",
            ),
        ),
        migrations.AddField(
            model_name="criteriaplaylist",
            name="parent",
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="grow.criteriaplaylist",
            ),
        ),
        migrations.AddField(
            model_name="criteriaplaylist",
            name="root",
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="root_descendants",
                to="grow.criteriaplaylist",
            ),
        ),
        migrations.AddField(
            model_name="criteriaplaylist",
            name="type",
            field=the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="the_music_tree_genre_kit.criteriatype"
            ),
        ),
        migrations.CreateModel(
            name="GenrePlaylist",
            fields=[],
            options={
                "db_table": "grow_genre_playlist",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("grow.criteriaplaylist",),
        ),
        migrations.CreateModel(
            name="TagPlaylist",
            fields=[],
            options={
                "db_table": "grow_tag_playlist",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("grow.criteriaplaylist",),
        ),
        migrations.AddIndex(
            model_name="manualplaylist",
            index=models.Index(fields=["_name"], name="manual_playlist_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="manualplaylist",
            constraint=models.CheckConstraint(
                condition=models.Q(("_name", ""), _negated=True), name="manual_playlist_non_empty_name"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(fields=["user", "uuid"], name="playlist_user_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(fields=["user", "content_type", "content_uuid"], name="grow_play_user_id_bc89eb_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrackplaylistrel",
            index=models.Index(fields=["user", "playlist"], name="grow_upload_user_id_02d361_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrackplaylistrel",
            index=models.Index(fields=["user", "uploaded_track"], name="grow_upload_user_id_885278_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrack",
            index=models.Index(fields=["user", "title"], name="grow_upload_user_id_a90e8e_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrack",
            index=models.Index(fields=["user", "genre"], name="grow_upload_user_id_a78281_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrack",
            index=models.Index(fields=["user", "album"], name="grow_upload_user_id_7d689d_idx"),
        ),
        migrations.AddIndex(
            model_name="criteriaplaylist",
            index=models.Index(fields=["criteria"], name="crit_playlist_criteria_idx"),
        ),
    ]
