# Generated by Django 5.2.8 on 2026-08-19 18:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0003_create_system_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('title', the_music_tree_api_kit.field.AppCharField(max_length=256)),
                ('track_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('language', the_music_tree_api_kit.field.AppCharField(blank=True, default=None, max_length=3, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'db_table': 'grow_track',
            },
        ),
        migrations.CreateModel(
            name='TrackPlaylistRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Track Playlist Relation',
                'verbose_name_plural': 'Track Playlist Relations',
                'db_table': 'grow_track_playlist_rel',
            },
        ),
        migrations.RemoveIndex(
            model_name='uploadedtrackplaylistrel',
            name='grow_upload_user_id_02d361_idx',
        ),
        migrations.RemoveIndex(
            model_name='uploadedtrackplaylistrel',
            name='grow_upload_user_id_885278_idx',
        ),
        migrations.RemoveField(
            model_name='uploadedtrackplaylistrel',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='uploadedtrackplaylistrel',
            name='uploaded_track',
        ),
        migrations.RemoveField(
            model_name='uploadedtrackplaylistrel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploadedtrack',
            name='playlists',
        ),
        migrations.RemoveIndex(
            model_name='uploadedtrack',
            name='grow_upload_user_id_a90e8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='uploadedtrack',
            name='grow_upload_user_id_a78281_idx',
        ),
        migrations.RemoveIndex(
            model_name='uploadedtrack',
            name='grow_upload_user_id_7d689d_idx',
        ),
        migrations.DeleteModel(
            name='UploadedTrack',
        ),
        migrations.CreateModel(
            name='UploadedTrack',
            fields=[
                ('track', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='uploadedtrack', serialize=False, to='grow.track')),
            ],
            options={
                'verbose_name': 'Uploaded Track',
                'verbose_name_plural': 'Uploaded Tracks',
                'db_table': 'grow_uploaded_track',
            },
            bases=('grow.track',),
        ),
        migrations.CreateModel(
            name='YoutubeTrack',
            fields=[
                ('track', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='youtubetrack', serialize=False, to='grow.track')),
                ('youtube_video_id', the_music_tree_api_kit.field.AppCharField(blank=True, default=None, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Youtube Track',
                'verbose_name_plural': 'Youtube Tracks',
                'db_table': 'grow_youtube_track',
            },
            bases=('grow.track',),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_of_album', to='grow.album'),
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='tracks_of_artist', to='grow.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks_of_criteria', to='grow.genre'),
        ),
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackplaylistrel',
            name='playlist',
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='grow.playlist'),
        ),
        migrations.AddField(
            model_name='trackplaylistrel',
            name='track',
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='grow.track'),
        ),
        migrations.AddField(
            model_name='trackplaylistrel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(related_name='tracks_of_playlist', through='grow.TrackPlaylistRel', to='grow.playlist'),
        ),
        migrations.DeleteModel(
            name='UploadedTrackPlaylistRel',
        ),
        migrations.AddIndex(
            model_name='trackplaylistrel',
            index=models.Index(fields=['user', 'playlist'], name='grow_track__user_id_928b41_idx'),
        ),
        migrations.AddIndex(
            model_name='trackplaylistrel',
            index=models.Index(fields=['user', 'track'], name='grow_track__user_id_1b2d91_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['user', 'title'], name='grow_track_user_id_9cd683_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['user', 'genre'], name='grow_track_user_id_ad54d6_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['user', 'album'], name='grow_track_user_id_ef8908_idx'),
        ),
    ]
