# Generated by Django 5.2.8 on 2026-08-27 18:06

import the_music_tree_api_kit.field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grow", "0013_create_prototype_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubetrack",
            name="youtube_video_id",
            field=the_music_tree_api_kit.field.AppCharField(max_length=11),
        ),
    ]
