# Generated by Django 5.2.8 on 2026-09-02 12:40

import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0017_criteria_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='essential_tracks',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='essential_genres', to='grow.youtubetrack'),
        ),
    ]
