# Generated by Django 5.2.8 on 2026-09-18 09:37

import the_music_tree_api_kit.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0019_delete_prototype_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='wikidata_id',
            field=the_music_tree_api_kit.field.AppCharField(blank=True, db_column='wikidata_id', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('wikidata_id__isnull', False)), fields=('wikidata_id', 'user'), name='unique_wikidata_id_per_user'),
        ),
    ]
