# Generated by Django 5.2.8 on 2026-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0020_genre_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
