# Generated by Django 5.2.8 on 2026-09-24 15:05

import uuid

import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field.foreign_key.AppForeignKey
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("grow", "0021_genre_is_excluded_genre_is_manually_edited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubetrack",
            name="is_manually_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="HistoryEntry",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("content_uuid", models.UUIDField(db_column="object_pk")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("parent_changed", "Parent changed"),
                            ("renamed", "Renamed"),
                            ("excluded", "Excluded"),
                            ("genre_changed", "Genre changed"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("actor_email", models.CharField(blank=True, max_length=255, null=True)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "History Entry",
                "verbose_name_plural": "History Entries",
                "db_table": "grow_history_entry",
                "indexes": [
                    models.Index(fields=["user", "content_type", "content_uuid"], name="grow_histor_user_id_8cb111_idx")
                ],
            },
        ),
    ]
