# Generated by Django 5.2.8 on 2026-09-25 14:37

import django.db.models.deletion
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0024_ownerless_reference_data'),
        ('the_music_tree_genre_kit', '0007_importrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='criteria',
            name='unique_canonical_name',
        ),
        migrations.RemoveConstraint(
            model_name='criteria',
            name='unique_name_per_user',
        ),
        migrations.AddField(
            model_name='criteria',
            name='additional_primary_parents',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='additional_primary_children', to='grow.criteria'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='allows_multiple_primary_parents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criteria',
            name='secondary_parents',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='secondary_children', to='grow.criteria'),
        ),
        migrations.AddField(
            model_name='genre',
            name='last_seen_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='the_music_tree_genre_kit.importrun'),
        ),
        migrations.AddField(
            model_name='genre',
            name='source',
            field=the_music_tree_api_kit.field.AppCharField(choices=[('pipeline', 'Pipeline'), ('app', 'App'), ('admin', 'Admin')], default='app', max_length=8),
        ),
    ]
