# Generated by Django 5.2.8 on 2026-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0027_case_insensitive_name_and_wikidata_id_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='has_name_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
