# Generated by Django 5.2.8 on 2026-09-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0028_genre_has_name_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('parent_changed', 'Parent changed'), ('renamed', 'Renamed'), ('excluded', 'Excluded'), ('genre_changed', 'Genre changed'), ('deleted', 'Deleted'), ('name_conflict_resolved', 'Name conflict resolved')], max_length=32),
        ),
    ]
