# Generated by Django 5.2.8 on 2026-09-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0029_history_action_name_conflict_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_unaccepted_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('parent_changed', 'Parent changed'), ('renamed', 'Renamed'), ('excluded', 'Excluded'), ('genre_changed', 'Genre changed'), ('deleted', 'Deleted'), ('name_conflict_resolved', 'Name conflict resolved'), ('root_accepted', 'Root accepted')], max_length=32),
        ),
    ]
