# Generated by Django 5.2.8 on 2026-10-01 16:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0033_criteria_tree_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('parent_changed', 'Parent changed'), ('renamed', 'Renamed'), ('excluded', 'Excluded'), ('genre_changed', 'Genre changed'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('name_conflict_resolved', 'Name conflict resolved'), ('root_accepted', 'Root accepted')], max_length=32),
        ),
        migrations.CreateModel(
            name='CurationEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('list_name', models.CharField(choices=[('accepted_canonical_roots', 'accepted_canonical_roots'), ('canonical_parent_additions', 'canonical_parent_additions'), ('capitalized_words', 'capitalized_words'), ('duplicate_genres', 'duplicate_genres'), ('indigenous_to_exclusions', 'indigenous_to_exclusions'), ('label_overrides', 'label_overrides'), ('main_parent', 'main_parent'), ('out_of_scope_genres', 'out_of_scope_genres'), ('overview_reclassifications', 'overview_reclassifications'), ('regional_overrides', 'regional_overrides'), ('regional_overview_additions', 'regional_overview_additions'), ('technique_genres', 'technique_genres'), ('theme_genres', 'theme_genres'), ('umbrella_canonical_genres', 'umbrella_canonical_genres'), ('accepted_non_genre_tags', 'accepted_non_genre_tags'), ('canonical_genre_pop_side', 'canonical_genre_pop_side'), ('genre_alias', 'genre_alias'), ('regional_secondary_parents', 'regional_secondary_parents')], max_length=64)),
                ('key', models.CharField(max_length=512)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grow_curation_entry',
                'constraints': [models.UniqueConstraint(fields=('list_name', 'key'), name='curation_entry_list_name_key_unique')],
            },
        ),
    ]
