# Generated by Django 5.2.8 on 2026-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0037_curation_history_list_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_on', models.DateTimeField(null=True)),
                ('applied_export_on', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'grow_curation_sync_state',
            },
        ),
    ]
