# Generated by Django 5.2.8 on 2026-10-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0039_genre_tree_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubetrack',
            name='youtube_unplayable_reason',
            field=models.CharField(blank=True, choices=[('not_found', 'Not Found'), ('not_embeddable', 'Not Embeddable'), ('private', 'Private'), ('not_processed', 'Not Processed'), ('region_whitelisted', 'Region Whitelisted')], max_length=32, null=True),
        ),
    ]
