# Generated by Django 5.2.8 on 2026-10-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0040_youtube_track_unplayable_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(choices=[('canonical_tree', 'Canonical Tree'), ('regional_tree', 'Regional Tree'), ('songs', 'Songs'), ('unresolved_genre_tags', 'Unresolved Genre Tags')])),
                ('imported_on', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField()),
                ('skipped_count', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'grow_import_run',
                'indexes': [models.Index(fields=['kind', '-imported_on'], name='grow_import_run_kind_idx')],
            },
        ),
    ]
