# Generated by Django 5.2.8 on 2026-10-06 12:57

from django.db import migrations, models

REASON = "more precise genre wins over the broader tag"
PRECEDENCES = [
    ("ska", "reggae"),
    ("rocksteady", "reggae"),
    ("ska punk", "ska"),
    ("ska punk", "punk"),
    ("pop rock", "pop"),
    ("pop rock", "rock"),
    ("soft rock", "rock"),
    ("soft rock", "pop"),
    ("classic rock", "rock"),
    ("alternative rock", "rock"),
    ("indie rock", "rock"),
    ("indie rock", "alternative rock"),
    ("folk rock", "rock"),
    ("folk rock", "folk"),
    ("hard rock", "rock"),
    ("heartland rock", "rock"),
    ("art rock", "rock"),
    ("blues rock", "blues"),
    ("blues rock", "rock"),
    ("grunge", "alternative rock"),
    ("grunge", "rock"),
    ("britpop", "alternative rock"),
    ("britpop", "rock"),
    ("punk", "rock"),
    ("dance-pop", "pop"),
    ("dance-pop", "dance"),
    ("synth-pop", "pop"),
    ("synth-pop", "electronic"),
    ("electropop", "pop"),
    ("electropop", "electronic"),
    ("teen pop", "pop"),
    ("europop", "pop"),
    ("alternative pop", "pop"),
    ("j-pop", "pop"),
    ("k-pop", "pop"),
    ("country pop", "country"),
    ("country pop", "pop"),
    ("house", "electronic"),
    ("downtempo", "electronic"),
    ("electro", "electronic"),
    ("ambient", "electronic"),
    ("trap", "hip hop"),
    ("pop rap", "hip hop"),
    ("alternative hip hop", "hip hop"),
    ("contemporary r&b", "r&b"),
    ("heavy metal", "metal"),
    ("black metal", "metal"),
    ("alternative metal", "metal"),
    ("alternative metal", "alternative rock"),
    ("banda sinaloense", "regional mexicano"),
]
"""The seeded `(musicbrainz_genre_name, over_musicbrainz_genre_name)` rows, inlined so this migration never
depends on the current curation registry or seed CSV."""


def seed(apps, schema_editor):
    CurationEntry = apps.get_model("grow", "CurationEntry")
    entries = CurationEntry.objects.filter(user=None, list_name="genre_precedence")
    for winner, loser in PRECEDENCES:
        key = f"{winner}\t{loser}"
        if not entries.filter(key=key).update(values={}, reason=REASON):
            CurationEntry.objects.create(user=None, list_name="genre_precedence", key=key, values={}, reason=REASON)


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0041_import_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='list_name',
            field=models.CharField(choices=[('accepted_canonical_roots', 'accepted_canonical_roots'), ('canonical_parent_additions', 'canonical_parent_additions'), ('capitalized_words', 'capitalized_words'), ('duplicate_genres', 'duplicate_genres'), ('indigenous_to_exclusions', 'indigenous_to_exclusions'), ('label_overrides', 'label_overrides'), ('main_parent', 'main_parent'), ('out_of_scope_genres', 'out_of_scope_genres'), ('overview_reclassifications', 'overview_reclassifications'), ('regional_overrides', 'regional_overrides'), ('regional_overview_additions', 'regional_overview_additions'), ('technique_genres', 'technique_genres'), ('theme_genres', 'theme_genres'), ('umbrella_canonical_genres', 'umbrella_canonical_genres'), ('accepted_non_genre_tags', 'accepted_non_genre_tags'), ('canonical_genre_pop_side', 'canonical_genre_pop_side'), ('genre_alias', 'genre_alias'), ('regional_secondary_parents', 'regional_secondary_parents'), ('genre_precedence', 'genre_precedence')], max_length=64),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
