# Generated by Django 5.2.8 on 2026-10-06 12:57

from functools import partial

from django.db import migrations, models

from grow.curation.rows import SEED_DIR, import_csv_dir, upsert_without_history


def seed(apps, schema_editor):
    CurationEntry = apps.get_model("grow", "CurationEntry")
    import_csv_dir(SEED_DIR, partial(upsert_without_history, CurationEntry), ["genre_precedence"])


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0041_import_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='list_name',
            field=models.CharField(choices=[('accepted_canonical_roots', 'accepted_canonical_roots'), ('canonical_parent_additions', 'canonical_parent_additions'), ('capitalized_words', 'capitalized_words'), ('duplicate_genres', 'duplicate_genres'), ('indigenous_to_exclusions', 'indigenous_to_exclusions'), ('label_overrides', 'label_overrides'), ('main_parent', 'main_parent'), ('out_of_scope_genres', 'out_of_scope_genres'), ('overview_reclassifications', 'overview_reclassifications'), ('regional_overrides', 'regional_overrides'), ('regional_overview_additions', 'regional_overview_additions'), ('technique_genres', 'technique_genres'), ('theme_genres', 'theme_genres'), ('umbrella_canonical_genres', 'umbrella_canonical_genres'), ('accepted_non_genre_tags', 'accepted_non_genre_tags'), ('canonical_genre_pop_side', 'canonical_genre_pop_side'), ('genre_alias', 'genre_alias'), ('regional_secondary_parents', 'regional_secondary_parents'), ('genre_precedence', 'genre_precedence')], max_length=64),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
