# Generated by Django 5.2.8 on 2026-10-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0042_genre_precedence_curation_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubetrack',
            name='musicbrainz_recording_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
