# Generated by Django 5.2.8 on 2026-10-08 12:56

import the_music_tree_api_kit.field
from django.db import migrations, models


def set_staging_unlogged(apps, schema_editor):
    # Staging rows are re-uploadable, so skipping the WAL is safe and much faster to COPY into.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE grow_song_import_staging SET UNLOGGED;")


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0043_youtube_track_musicbrainz_recording_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('committed_on', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'grow_song_import_run',
            },
        ),
        migrations.AlterField(
            model_name='youtubetrack',
            name='youtube_video_id',
            field=the_music_tree_api_kit.field.AppCharField(blank=True, max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='SongImportStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.BigIntegerField()),
                ('part', models.PositiveIntegerField()),
                ('musicbrainz_recording_id', models.UUIDField()),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('youtube_video_id', models.TextField(null=True)),
                ('youtube_unplayable_reason', models.TextField(null=True)),
                ('genre_name', models.TextField(null=True)),
            ],
            options={
                'db_table': 'grow_song_import_staging',
                'indexes': [models.Index(fields=['run_id', 'part'], name='grow_song_staging_run_part_idx')],
            },
        ),
        migrations.RunPython(set_staging_unlogged, migrations.RunPython.noop),
    ]
