# Generated by Django 5.2.8 on 2026-10-08 18:00

import the_music_tree_api_kit.field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grow", "0044_bulk_song_import"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="_name",
            field=the_music_tree_api_kit.field.AppCharField(db_column="name", default=None, max_length=2048),
        ),
    ]
