from the_music_tree_api_kit.private_unique_resource.Fields import Fields as PrivateUniqueResourceFields


class Fields(PrivateUniqueResourceFields):
    NAME_PUBLIC = "name"
    NAME_INTERNAL = f"_{NAME_PUBLIC}"
    UPLOADED_TRACKS_NOT_ARCHIVED_INTERNAL = "uploaded_tracks_not_archived"
    UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC = "uploaded_tracks"
    UPLOADED_TRACKS_NOT_ARCHIVED_SORTED_INTERNAL = f"{UPLOADED_TRACKS_NOT_ARCHIVED_INTERNAL}_sorted"
    UPLOADED_TRACKS_NOT_ARCHIVED_SORTED_PUBLIC = f"{UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC}_sorted"
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_INTERNAL = f"{UPLOADED_TRACKS_NOT_ARCHIVED_INTERNAL}_count"
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = f"{UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC}_count"
    UPLOADED_TRACKS_ARCHIVED_COUNT_INTERNAL = "uploaded_tracks_archived_count"
    UPLOADED_TRACKS_ARCHIVED_COUNT_PUBLIC = UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC + "_archived_count"
